baseURL = "https://lionsconvention2020.co.za"
languageCode = "en-za"
title = "Lions Multiple District 410 2020 Convention"
theme = "beautifulhugo" 
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = false
pygmentsCodeFences = false
pygmentsCodefencesGuessSyntax = false

[blackfriday]
  fractions = false

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  # logo = "img/compass_round.png"
  favicon = "img/favicon.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = false
  socialShare = false
  delayDisqus = false
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
   
#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
   name = "Lions Clubs International Multiple District 410"
   website = "https://lionsclubs.co.za"
#   email = "youremail@domain.com"
   facebook = "Lions-MD-410-2020-Convention-305534583657980/"
#   googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
#   github = "username"
#   gitlab = "username"
#   bitbucket = "username"
#   twitter = "username"
#   reddit = "username"
#   linkedin = "username"
#   xing = "username"
#   stackoverflow = "users/XXXXXXX/username"
#   snapchat = "username"
#   instagram = "username"
#   youtube = "user/username" # or channel/channelname
#   soundcloud = "username"
#   spotify = "username"
#   bandcamp = "username"
#   itchio = "username"
#   vk = "username"
#   paypal = "username"
#   telegram = "username"
#   500px = "username"

[[menu.main]]
    name = "Registration Form"
    url = "registration"
    weight = 1

[[menu.main]]
    name = "Accommodation & Venue"
    identifier = "accommodation"
    weight = 2

[[menu.main]]
    name = "Accommodation"
    url = "accommodation"
    parent = "accommodation"
    weight = 2

[[menu.main]]
    name = "Venue"
    parent = "accommodation"
    url = "venue"
    weight = 2

[[menu.main]]
    name = "Program"
    url = "program"
    weight = 3

[[menu.main]]
    name = "News and Newsletters"
    identifier = "news"
    url = "news"
    weight = 4

[[menu.main]]
    name = "Launch Poster"
    url = "news/launch_poster"
    parent = "news"
    weight = 4

[[menu.main]]
    name = "International Guest"
    url = "guest"
    weight = 5

[[menu.main]]
    name = "Convention Committee"
    url = "committee"
    weight = 6
